export default function loadBackgrounds(p) {
  switch (p){
    case 1 : return [ 
"                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                BBBB",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "     B        B     ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "        BBBB        ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "BBBBB          BBBBB",
    "BBBBB          BBBBB",
    "BBBBB          BBBBB",
    "BBBBB          BBBBB",
    "BBBBB          BBBBB",
    "BBBBB          BBBBB",
		"BBBBB          BBBBB",]
  case 2: return [
    "                    ",
    "B                  B",
    "B                  B",
    "B                  B",
    "B                  B",
    "B                  B",
    "B     BBBBBBBBBBBBBB",
    "B     BBBBBBBBBBBBBB",
    "B                  B",
    "B                  B",
    "B                  B",
    "B   BBBBBBB        B",
    "B                  B",
    "B                  B",
    "B                  B",
    "BBBBBBBBBBBBBBB    B",
    "BBBBBBBBBBBBBBB    B",
    "B                  B",
    "B                  B",
    "B       BBB        B",
    "B  BBB  BBB   BBB  B",
    "B  BBB  BBB   BBB  B",
    "B       BBB        B",
    "B       BBB        B",
    "B       BBB        B",
    "B  BBBBBBBBBBBBB   B",
    "B  BBBBBBBBBBBBB   B",
    "B  BBBBBBBBBBBBB   B",
    "B                  B",
    "B                  B",
    "B                  B",
    "B    BB            B",
    "B    BB    BB      B",
    "B    BB    BB      B",
    "BBBBBBBBBBBBBBBBBBBB",]
 case 3 : return [
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"       B            ",
"       B            ",
"       B            ",
"       B            ",
"                    ",
"                    ",
"                    ",
"         BB         ",
"         BB         ",]
case 4 : return [
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"BBBB                ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"                    ",
"BBBB                ",
"BBBB                ",
"BBBB      BBB       ",]
}
}