export default function loadBackgrounds(p) {
  switch (p){
    case 1 : return [ 
    "1==================2",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBB    ",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBB BBBBBBBB BBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "|BBBBBBBBBBBBBBBBBB|",
    "4====2BBBBBBBB1====3",
    "     |BBBBBBBB|     ",
    "     |BBBBBBBB|     ",
    "     |BBBBBBBB|     ",
    "     |BBBBBBBB|     ",
    "     |BBBBBBBB|     ",
    "     |BBBBBBBB|     ",
		"     4========3     ",]
  case 2: return [
    "                    ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBB              ",
    " BBBBB              ",
    " BBBBBBBBBBBBBBBBBB ",
    "|BBBBBBBBBBBBBBBBBB|",
    " BBBBBBBBBBBBBBBBBB ",
    " BBB       BBBBBBBB ",
    " BBB       BBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    "               BBBB ",
    "               BBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBB   BBBBBBBB ",
    " BB   BB   BBB   BB ",
    " BB   BB   BBB   BB ",
    " BBBBBBB   BBBBBBBB ",
    " BBBBBBB   BBBBBBBB ",
    " BBBBBBB   BBBBBBBB ",
    " BB             BBB ",
    " BB             BBB ",
    " BB             BBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBBBBBBBBBBBBBBBB ",
    " BBBB  BBBBBBBBBBBB ",
    " BBBB  BBBB  BBBBBB ",
    " BBBB  BBBB  BBBBBB ",
    "                    ",]
 case 3 : return []
  }
}