import patrol from "../behavior/patrol"
import spike_ball from "../object/spike_ball"
import slider from "../object/slider"

export default function loadLevelConf() {
  return {
	// grid size
	width: 16, 
	height: 16,
	// define each object as a list of components
	"=": () => [
		sprite("horizontal_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "|": () => [
		sprite("vertical_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "1": () => [
		sprite("top_left_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "2": () => [
		sprite("top_right_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "3": () => [
		sprite("bottom_right_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "4": () => [
		sprite("bottom_left_border"),
		area(),
		solid(),
		origin("bot"),
    layer("lvl"),
	],
   "^": () => [
		sprite("floor_spike"),
		area({ scale: 0.7, }),
    solid(),
		origin("bot"),
		"danger",
    "spike",
    layer("lvl"),
	],
    "v": () => [
		sprite("roof_spike"),
		area({ scale: 0.8, }),
    solid(),
		origin("bot"),
		"danger",
    "spike",
    layer("lvl"),
	],
    ">": () => [
		sprite("left_wall_spike"),
		area({ scale: 0.8, }),
    solid(),
		origin("bot"),
		"danger",
    "spike",
    layer("lvl"),
	],
    "<": () => [
		sprite("right_wall_spike"),
		area({ scale: 0.8, }),
    solid(),
		origin("bot"),
		"danger",
    "spike",
    layer("lvl"),
	],
	 "p": () => [
		sprite("door"),
		area({ scale: 0.5,}),
    solid(),
		origin("bot"),
    "door",
    layer("lvl"),
	],
	 "c": () => [
		sprite("coin"),
		area(),
		origin("bot"),
    "coin",
    layer("lvl"),
	],
   "B": () => [
		sprite("background"),
		origin("bot"),
    layer("lvl"),
	],
    "e": () => [
		sprite("enemy"),
		origin("bot"),
    solid(), 
    area({ width: 16, height: 6. }),
    patrol(),
    layer("lvl"),
	],
    "s": () => [
		sprite("spike_ball"),
		origin("bot"),
    solid(), 
    body(), 
    area({ width: 8, height: 8. }),
    spike_ball(),
    "danger",
    layer("lvl"),
	],
    "+": () => [
		sprite("cube"),
		origin("bot"),
    solid(), 
    area(),
    slider('v'),
    layer("lvl"),
	],
    "0": () => [
		sprite("cube"),
		origin("bot"),
    solid(), 
    area(),
    scale(0.5),
    layer("lvl"),
  ],
  "]": () => [
		sprite("left_end_border"),
		origin("bot"),
    solid(), 
    area(),
    layer("lvl"),
  ],
  "[": () => [
		sprite("right_end_border"),
		origin("bot"),
    solid(), 
    area(),
    layer("lvl"),
  ],
  "n": () => [
		sprite("top_end_border"),
		origin("bot"),
    solid(), 
    area(),
    layer("lvl"),
  ],
  "u": () => [
		sprite("bottom_end_border"),
		origin("bot"),
    solid(), 
    area(),
    layer("lvl"),
  ],
  "(": () => [
		sprite("right_cannon"),
		origin("bot"),
    solid(), 
    area({ width: 8, height: 14. }),
    layer("lvl"),
    "cannon_right",
  ],
   ")": () => [
		sprite("left_cannon"),
		origin("bot"),
    solid(), 
    area({ width: 8, height: 14. }),
    layer("lvl"),
    "cannon_left",
  ],
    /*
   "r": () => [
		sprite("conveyor", {anim: "right", }),
		origin("bot"),
    solid(), 
    area({scale: 0.9 }),
    "conveyor",
	],
   "C": () => [
		sprite("conveyor", {anim: "center", }),
		origin("bot"),
    solid(), 
    area({scale: 0.9 }),
    "conveyor",
	],
  "l": () => [
		sprite("conveyor", {anim: "left", }),
		origin("bot"),
    solid(), 
    area({scale: 0.9 }),
    "conveyor",
	],
    */
 }
}